[package]
name = "bench_scale_4"
type = "bin"
compiler_version = ">=1.0.0"

[dependencies]
zkemail = { path = "../../../../lib" }
sha256 = { git = "https://github.com/noir-lang/sha256", tag = "v0.1.2" }
